# Generated by Django 6.0.4 on 2026-07-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=264, unique=True)),
                ('Last_Name', models.CharField(max_length=264, unique=True)),
                ('Email', models.EmailField(max_length=264, unique=True)),
            ],
        ),
    ]
